stages:
  - format
  - plan
  - apply
  - destroy
  - publish

variables:
  AWS_ROLE_NAME: gitlab_runner
  AWS_ACCOUNT_ID: 471871437096
  AWS_PROFILE_NAME: cmdlabtf-master

format:
  stage: format
  tags:
    - cmd
  script:
    - make formatCheck

plan-aws2:
  stage: plan
  tags:
    - cmd
  script:
    - make plan
  variables:
    TF_VAR_resource_suffix: aws2
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

plan-aws3:
  stage: plan
  tags:
    - cmd
  script:
    - make plan
  variables:
    TF_VAR_resource_suffix: aws3
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

apply-aws2:
  stage: apply
  tags:
    - cmd
  script:
    - make apply
  variables:
    TF_VAR_resource_suffix: aws2
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

apply-aws3:
  stage: apply
  tags:
    - cmd
  script:
    - make apply
  variables:
    TF_VAR_resource_suffix: aws3
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

destroy-aws2:
  stage: destroy
  tags:
    - cmd
  script:
    - make destroy
  variables:
    TF_VAR_resource_suffix: aws2
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

destroy-aws3:
  stage: destroy
  tags:
    - cmd
  script:
    - make destroy
  variables:
    TF_VAR_resource_suffix: aws3
    SUBFOLDER: tests/${TF_VAR_resource_suffix}

publish:
  stage: publish
  tags:
    - cmd
  script:
    - make publish
  variables:
    GIT_STRATEGY: clone
  only:
    - master
    - tags
